theme: minima
title: Igor Alexandre mathematics page
author: Igor Alexandre Santoro Caetano 
Description: Hi! I am a second year bachelor student from Sweden doing some "important" research on special functions. This is my homepage 
where I write about some of my results and interests which are bracket methods, homotopy theory, Ramunujan's master theorem, number theory  and arithmetic geometry
